### ISSUE TITLE
TypeError: Router.use() requires a middleware function but got a Null

### ISSUE THREAD

**Issue by katoumorisan** [ddssingsong/webrtc_server_node#12]
some errors come out when I have done proceeding the last procedure of the steps as your blog says:
`
[root@webrtc-server webrtc_server_node]# node server.js
/root/webrtc_server_node/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^

TypeError: Router.use() requires a middleware function but got a Null
    at Function.use (/root/webrtc_server_node/node_modules/express/lib/router/index.js:458:13)
    at Function.<anonymous> (/root/webrtc_server_node/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/root/webrtc_server_node/node_modules/express/lib/application.js:217:7)
    at Object.<anonymous> (/root/webrtc_server_node/server.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

**Comment by CodeIsWorld** [comment]
i got this error too.

**Comment by wsdydeni** [comment]
```js
app.use([path], function(request, response, next){})

app.use(express.static(path.join(__dirname, '/')));
```
only set static path, no funcation

**Comment by hotsmile** [comment]
同样的问题
