### ISSUE TITLE
i can't run the server right by using node cmd

### ISSUE THREAD

**Issue by hotsmile** [ddssingsong/webrtc_server_node#17]
i run  node server.js  cmd
but i got the error.

```
D:\intelj\webrtc_server_node\node_modules\express\lib\router\index.js:464
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^

TypeError: Router.use() requires a middleware function but got a Null
    at Function.use (D:\intelj\webrtc_server_node\node_modules\express\lib\router\index.js:464:13)
    at Function.<anonymous> (D:\intelj\webrtc_server_node\node_modules\express\lib\application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\intelj\webrtc_server_node\node_modules\express\lib\application.js:217:7)
    at Object.<anonymous> (D:\intelj\webrtc_server_node\server.js:9:5)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by andeyeluguo** [comment]
一样的错误，作者可以出来解释一下吗

**Comment by xiaoliang16** [comment]
把server.js  文件中的 第9行： app.use(express.static(path.join(__dirname, 'public')), null);
改为： app.use(express.static(path.join(__dirname, 'public')));
再次运行可以成功。

**Comment by xiaoliang16** [comment]
> i run node server.js cmd but i got the error.
> 
> ```
> D:\intelj\webrtc_server_node\node_modules\express\lib\router\index.js:464
>       throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
>       ^
> 
> TypeError: Router.use() requires a middleware function but got a Null
>     at Function.use (D:\intelj\webrtc_server_node\node_modules\express\lib\router\index.js:464:13)
>     at Function.<anonymous> (D:\intelj\webrtc_server_node\node_modules\express\lib\application.js:220:21)
>     at Array.forEach (<anonymous>)
>     at Function.use (D:\intelj\webrtc_server_node\node_modules\express\lib\application.js:217:7)
>     at Object.<anonymous> (D:\intelj\webrtc_server_node\server.js:9:5)
>     at Module._compile (node:internal/modules/cjs/loader:1165:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
>     at Module.load (node:internal/modules/cjs/loader:1043:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> ```
把server.js 文件中的 第9行： app.use(express.static(path.join(__dirname, 'public')), null);
改为： app.use(express.static(path.join(__dirname, 'public')));
再次运行可以成功。

**Comment by ddssingsong** [comment]
赞

**Comment by woeinsd** [comment]
express.static(path.join(__dirname, 'public'))：这是一个中间件函数，用于提供 public 目录中的静态文件。path.join(__dirname, 'public') 会生成 public 目录的绝对路径。
app.use(...)：将这个中间件添加到 Express 应用中，使得所有请求都可以访问 public 目录中的文件。
, null：这个部分是多余的，因为 app.use() 只需要一个中间件函数作为参数。传递 null 会导致您之前遇到的错误。
为了修复这个问题，您可以将代码修改为：
