### ISSUE TITLE
fail to excute node server.js 

### ISSUE THREAD

**Issue by Chambers1994** [ddssingsong/webrtc_server_node#6]
I hava try twice, but it didn't work, I config my /etc/turnserver.conf based this github guidance, but then:
air@air-G3-3590:~/webRTC/webrtc_server$ node server.js 
/home/air/webRTC/webrtc_server/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^

TypeError: Router.use() requires a middleware function but got a Null
    at Function.use (/home/air/webRTC/webrtc_server/node_modules/express/lib/router/index.js:458:13)
    at Function.<anonymous> (/home/air/webRTC/webrtc_server/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/air/webRTC/webrtc_server/node_modules/express/lib/application.js:217:7)
    at Object.<anonymous> (/home/air/webRTC/webrtc_server/server.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
air@air-G3-3590:~/webRTC/webrtc_server$ node server.js 

Your help will be appreciated!

**Comment by ZhuoSir** [comment]
解决了吗

**Comment by woeinsd** [comment]
我也遇到这个问题
